# Generated by Django 5.0.6 on 2024-07-28 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libon', '0003_alter_carrito_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='cliente',
            new_name='usuario',
        ),
    ]
