from .usuario import Usuario
from .autor import Autor
from .boleta import Boleta
from .categoria import Categoria
from .ejemplar import Ejemplar
from .historial import Historial
from .prestamos import Prestamos
from .tema import Tema
from .venta import Venta